// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_PSp_VYT3Yewp0zakUmQlTnwkcYDIUbg',
    appId: '1:134634382504:web:98484ac6349c5ead754e9d',
    messagingSenderId: '134634382504',
    projectId: 'fitnesss-a98ff',
    authDomain: 'fitnesss-a98ff.firebaseapp.com',
    storageBucket: 'fitnesss-a98ff.firebasestorage.app',
    measurementId: 'G-Z252XPKT9B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBm9jRkP4101nDZR9yRCmti9DOOIK5iglU',
    appId: '1:134634382504:android:bb586f4f68d9c169754e9d',
    messagingSenderId: '134634382504',
    projectId: 'fitnesss-a98ff',
    storageBucket: 'fitnesss-a98ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP0y8Ynpwot4OBmhiJGlLmGXd-lzZ4qSI',
    appId: '1:134634382504:ios:6fba1db3199a08cd754e9d',
    messagingSenderId: '134634382504',
    projectId: 'fitnesss-a98ff',
    storageBucket: 'fitnesss-a98ff.firebasestorage.app',
    iosBundleId: 'com.example.fitnessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAP0y8Ynpwot4OBmhiJGlLmGXd-lzZ4qSI',
    appId: '1:134634382504:ios:6fba1db3199a08cd754e9d',
    messagingSenderId: '134634382504',
    projectId: 'fitnesss-a98ff',
    storageBucket: 'fitnesss-a98ff.firebasestorage.app',
    iosBundleId: 'com.example.fitnessApp',
  );
}
